build:
  image: firecyberice/rpi-docker:1.10.0-dev
  extra_hosts:
    - docker
  environment:
    - DOCKER_HOST=tcp://localhost:2375

compose:
  docker:
    privileged: true
    image: firecyberice/rpi-docker:1.10.0-dev-dind

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - '4.6.1'
      - '4.6'
      - '4'
      - argon
    file: 4.6/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 4.6.1-onbuild
      - 4.6-onbuild
      - 4-onbuild
      - argon-onbuild
    file: 4.6/onbuild/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 4.6.1-wheezy
      - 4.6-wheezy
      - 4-wheezy
      - argon-wheezy
    file: 4.6/wheezy/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 4.6.1-slim
      - 4.6-slim
      - 4-slim
    file: 4.6/slim/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - '6.9.1'
      - '6.9'
      - '6'
      - latest
      - boron
    file: 6.9/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 6.9.1-onbuild
      - 6.9-onbuild
      - 6-onbuild
      - onbuild
      - boron-onbuild
    file: 6.9/onbuild/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 6.9.1-wheezy
      - 6.9-wheezy
      - 6-wheezy
      - wheezy
      - boron-wheezy
    file: 6.9/wheezy/Dockerfile
    when:
      branch: master

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-node
    tag:
      - 6.9.1-slim
      - 6.9-slim
      - 6-slim
      - slim
      - boron-slim
    file: 6.9/slim/Dockerfile
    when:
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: buildstatus
    username: Drone
    when:
      started: false
      success: true
      failure: true
